### ISSUE TITLE
远程转发示例

### ISSUE THREAD

**Issue by emptyteeth** [wangdoc/ssh-tutorial#21]
现有的这个示例场景比较特殊，是否可以补充一种比较常用的示例以便于理解，以下是大致描述

ssh -R 8080:localhost:80 -N my.public.server
在内网环境下的本机localhost:80开启一个web服务
通过远程转发将这个80端口映射到具有公网IP的my.public.server主机的8080端口上
使得任何人都可以通过my.public.server:8080这个地址访问到本机80端口的web服务

ssh -R [remote-address:]remote-port:target-address:target-port -N remotehost
把本地路由可达的目标端口映射到远程主机的特定端口上，使可通过远程主机的特定端口来访问目标端口
remote address和remote port指定远程的监听地址和端口
target address和target port指定实际被访问的地址和端口，这个地址可以是任何本地路由可达的地址

ref: <https://www.ssh.com/academy/ssh/tunneling/example#remote-forwarding>

**Comment by ruanyf** [comment]
谢谢提醒，已经加入这个例子了。
