### ISSUE TITLE
AES 128表述不准确

### ISSUE THREAD

**Issue by Cyl18** [wangdoc/ssh-tutorial#22]
SSH 客户端一节中
> TLS：协议
RSA：密钥交换算法
AES：加密算法
128：加密强度
CBC：加密模式
SHA：数字签名的 Hash 函数

128并不是简单地指加密强度 改成密钥长度会好一些
然后TLS的协议说清楚是什么协议（（

**Comment by ruanyf** [comment]
谢谢指出，已经修改了。
