### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by lfpdev** [wangdoc/ssh-tutorial#23]
[命令行配置项](https://wangdoc.com/ssh/client.html#ssh-%E5%91%BD%E4%BB%A4%E8%A1%8C%E9%85%8D%E7%BD%AE%E9%A1%B9)
-i 默认值为 `~/.ssh/id_rsa`

**Comment by ruanyf** [comment]
DSA 算法对应的是 id_dsa，我把 RSA 算法加上吧。https://linux.die.net/man/1/ssh
