### ISSUE TITLE
证书登录流程

### ISSUE THREAD

**Issue by sheyue1** [wangdoc/ssh-tutorial#27]
能否详细写一下证书登录的验证过程
![image](https://user-images.githubusercontent.com/68190563/145987917-8f64ff13-00bb-4bb3-aebc-ab5a57d0a0fb.png)
是怎么检查是否有效的

**Comment by ruanyf** [comment]
跟 HTTPS 是一个原理，可以看浏览器的加密通信。

**Comment by sheyue1** [comment]
好的，谢谢老师
