### ISSUE TITLE
ssh服务器怎么确定用哪个公钥去解密客户端发来的加密签名？

### ISSUE THREAD

**Issue by JoeDylon** [wangdoc/ssh-tutorial#32]
### 密钥登录的过程
SSH 密钥登录分为以下的步骤。

预备步骤，客户端通过ssh-keygen生成自己的公钥和私钥。

第一步，手动将客户端的公钥放入远程服务器的指定位置。

第二步，客户端向服务器发起 SSH 登录的请求。

第三步，服务器收到用户 SSH 登录的请求，发送一些随机数据给用户，要求用户证明自己的身份。

第四步，客户端收到服务器发来的数据，使用私钥对数据进行签名，然后再发还给服务器。

第五步，服务器收到客户端发来的加密签名后，使用**对应的公钥**解密，然后跟原始数据比较。如果一致，就允许用户登录。

请问其中对应的公钥是怎么确定的？

**Comment by ruanyf** [comment]
可以看一下 known_hosts 文件，里面有主机的哈希。
