### ISSUE TITLE
文中关于 ssh 客户端配置文件的 Host * 设置的论述存在问题

### ISSUE THREAD

**Issue by Borne912** [wangdoc/ssh-tutorial#34]
文章的这个部分，具体如下图所示：
![](https://raw.githubusercontent.com/Yapwn/BlogDataBase/master/929481dccbd71dce9b99db2a30264bd.png)
如上图所示，`Host *` 如果写在了 `Host remoteserver ` 前面，就无法实现像文中所说的后续覆盖的效果了，因为：
![](https://raw.githubusercontent.com/Yapwn/BlogDataBase/master/b3657d854e431bd1a51c141258bfcbb.png)

> 官方文档指出：For each parameter, the first obtained value will be used.(对于每个参数，将使用第一个获得的值)

当 `Host *` 写在前面时，`Port 2222` 会被首先使用，下面在补充一个 ssh 连接的过程：
![](https://raw.githubusercontent.com/Yapwn/BlogDataBase/master/20230905154752.png)

综上所述，要实现文章中所说的写法，应该这样写：
```shell
Host remoteserver
     HostName remote.example.com
     User neo
     Port 2112

Host *
     Port 2222
```
即：`Host *`  应该被放到配置文件的最末尾，进行补充设置。

**Comment by ruanyf** [comment]
谢谢指出，已经改正了。
