### ISSUE TITLE
ssh 没有 -h 或 -help 参数

### ISSUE THREAD

**Issue by cncsl** [wangdoc/ssh-tutorial#7]
试了 windows 上的 *OpenSSH_for_Windows_7.7p1* 和 Centos7 上的 *OpenSSH_8.0p1, OpenSSL 1.0.2k-fips*，都没有 `-h` 或 `-help` 参数，请问 client.md 文中的叙述是否有误，什么版本的 OpenSSH 具有该命令？

**Comment by ruanyf** [comment]
谢谢指出，确实没有`-h`这个参数，已经更正。
